openapi: '3.0.0'
info:
  version: '0.1.0'
  title: 'Xena OpenAutomation REST API'
  description: XOA REST API for test suite integration with third-party test automation framework

servers:
  - url: 'localhost'

paths:
  /api/{{api_version}}:
    parameters:
      - name: api_version
        description: API version
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/APIVersion'
    get:
      summary: Get node information
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInfo'

  /api/{{api_version}}/ping:
    parameters:
      - name: api_version
        description: API version
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/APIVersion'
    get:
      summary: Ping the node
      responses:
        '200':
          description: Pong from the node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PongInfo'
  /api/{{api_version}}/testers:
    parameters:
      - name: api_version
        description: API version
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/APIVersion'
    get:
      summary: List testers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TesterList'
    post:
      summary: Add tester
      responses:
        '201':
          description: Tester Added
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/TesterId'
        '202':
          description: Tester Already Added
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/TesterId'
        '422':
          description: Bad tester info
  /api/{{api_version}}/testers/{{tester_id}}:
    parameters:
      - name: api_version
        description: API version
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/APIVersion'
      - name: tester_id
        description: Tester identifier
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/TesterId'
    delete:
      summary: Remove tester
      responses:
        '200':
          description: OK
  /api/{{api_version}}/testers/{{tester_id}}/control:
    parameters:
      - name: api_version
        description: API version
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/APIVersion'
      - name: tester_id
        description: Tester identifier
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/TesterId'
    post:
      summary: Connect to an added tester
      responses:
        '200':
          description: Connection OK
    delete:
      summary: Disconnect a tester
      responses:
        '200':
          description: Disconnection OK
    patch:
      summary: Configure a tester
      responses:
        '200':
          description: 'Successfully configured the tester'
      requestBody:
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/TesterObject'
  /api/{{api_version}}/test:
    parameters:
      - name: api_version
        description: API version
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/APIVersion'
    post:
      summary: Start test
      responses:
        '200':
          description: Test is started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestId'
      requestBody:
        content:
              application/json:
                schema:
                  $ref: '#/components/schemas/TestConfiguration'
    delete:
      summary: Stop test
      responses:
        '200':
          description: Test is stopped
    patch:
      summary: Pause test
      responses:
        '200':
          description: Test is paused
  /api/{{api_version}}/subscribe/resources:
    parameters:
      - name: api_version
        description: API version
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/APIVersion'
    post:
      summary: Subscribe to Test Resource Status
      responses:
        '201':
          description: Successfully subscribed to test resource status change
      requestBody:
        content:
              application/json:
                schema:
                  $ref: '#/components/schemas/SubscriptionInfo'


components:
  schemas:
    $ref: "./schemas/_index.yaml"


security:
  - ApiKey: []