title: FlowCreationConfig
type: object
properties:
    flow_creation_type:
      title: Flow Creation Type
      $ref: './FlowCreationType.yaml'
    tid_allocation_scope:
      title: Test Payload ID Allcation Scope
      $ref: './TidAllocationScope.yaml'
    mac_base_address:
      title: MAC Base Address
      type: string
      pattern: "[0-9A-Fa-f]{2}:[0-9A-Fa-f]{2}:[0-9A-Fa-f]{2}"