title: FrameSizeConfiguration
type: object
properties:
  packet_size_type:
    $ref: './FrameSizeType.yaml'
  custom_packet_sizes:
    title: Custom Packet Sizes
    type: array
    items:
      type: integer
      minimum: 0
  fixed_packet_start_size:
    title: Fixed Packet Start Size
    minimum: 0
    type: integer
  fixed_packet_end_size:
    title: Fixed Packet End Size
    minimum: 0
    type: integer
  fixed_packet_step_size:
    title: Fixed Packet Step Size
    minimum: 0
    type: integer
  varying_packet_min_size:
    title: Varying Packet Min Size
    minimum: 0
    type: integer
  varying_packet_max_size:
    title: Varying Packet Max Size
    minimum: 0
    type: integer
  mixed_length_config:
    $ref: './FrameSizesOptions.yaml'
  mixed_sizes_weights:
    title: Mixed Sizes Weights
    default:
      - 0
      - 0
      - 0
      - 0
      - 57
      - 3
      - 5
      - 1
      - 2
      - 5
      - 1
      - 4
      - 4
      - 18
      - 0
      - 0
    type: array
    items:
      type: integer
      minimum: 0
required:
  - packet_size_type
  - custom_packet_sizes
  - fixed_packet_start_size
  - fixed_packet_end_size
  - fixed_packet_step_size
  - varying_packet_min_size
  - varying_packet_max_size
  - mixed_length_config