title: ProtocolSegmentProfileConfig
type: object
properties:
  id:
    type: string
    format: uuid
  segments:
    title: Header Segments
    default: []
    type: array
    items:
      $ref: './ProtocolSegment.yaml'
required:
  - id
  - segments