title: TestConfiguration
type: object
properties:
  flow_creation_type:
    $ref: './FlowCreationType.yaml'
  tid_allocation_scope:
    $ref: './TidAllocationScope.yaml'
  mac_base_address:
    title: Mac Base Address
    type: string
  enable_speed_reduction_sweep:
    title: Enable Speed Reduction Sweep
    type: boolean
  use_port_sync_start:
    title: Use Port Sync Start
    type: boolean
  port_stagger_steps:
    title: Port Stagger Steps
    minimum: 0
    type: integer
  outer_loop_mode:
    $ref: './OuterLoopMode.yaml'
  mac_learning_mode:
    $ref: './MACLearningMode.yaml'
  mac_learning_frame_count:
    title: Mac Learning Frame Count
    minimum: 0
    type: integer
  toggle_port_sync_config:
    $ref: './TogglePortSyncConfig.yaml'
  learning_rate_pct:
    title: Learning Rate Pct
    type: number
  learning_duration_second:
    title: Learning Duration Second
    minimum: 0
    type: integer
  use_flow_based_learning_preamble:
    title: Use Flow Based Learning Preamble
    type: boolean
  flow_based_learning_frame_count:
    title: Flow Based Learning Frame Count
    minimum: 0
    type: integer
  delay_after_flow_based_learning_ms:
    title: Delay After Flow Based Learning Ms
    minimum: 50
    type: integer
  arp_refresh_enabled:
    title: Arp Refresh Enabled
    type: boolean
  arp_refresh_period_second:
    title: Arp Refresh Period Second
    default: 4000
    type: number
  use_gateway_mac_as_dmac:
    title: Use Gateway Mac As Dmac
    type: boolean
  should_stop_on_los:
    title: Should Stop On Los
    type: boolean
  delay_after_port_reset_second:
    title: Delay After Port Reset Second
    minimum: 0
    type: integer
  topology:
    $ref: './TestTopology.yaml'
  direction:
    $ref: './TrafficDirection.yaml'
  frame_sizes:
    $ref: './FrameSizeConfiguration.yaml'
  use_micro_tpld_on_demand:
    title: Use Micro Tpld On Demand
    type: boolean
  payload_type:
    $ref: './PayloadTypeStr.yaml'
  payload_pattern:
    title: Payload Pattern
    type: string
  multi_stream_config:
    $ref: './MultiStreamConfig.yaml'
  repeat_test_until_stopped:
    title: Repeat Test Until Stopped
    default: false
    type: boolean
required:
  - flow_creation_type
  - tid_allocation_scope
  - mac_base_address
  - enable_speed_reduction_sweep
  - use_port_sync_start
  - port_stagger_steps
  - outer_loop_mode
  - mac_learning_mode
  - mac_learning_frame_count
  - toggle_port_sync_config
  - learning_rate_pct
  - learning_duration_second
  - use_flow_based_learning_preamble
  - flow_based_learning_frame_count
  - delay_after_flow_based_learning_ms
  - arp_refresh_enabled
  - use_gateway_mac_as_dmac
  - should_stop_on_los
  - delay_after_port_reset_second
  - topology
  - direction
  - frame_sizes
  - use_micro_tpld_on_demand
  - payload_type
  - payload_pattern
  - multi_stream_config