title: TestTypesConfiguration
type: object
properties:
  throughput_test:
    $ref: './ThroughputTest.yaml'
  latency_test:
    $ref: './LatencyTest.yaml'
  frame_loss_rate_test:
    $ref: './FrameLossRateTest.yaml'
  back_to_back_test:
    $ref: './BackToBackTest.yaml'
required:
  - throughput_test
  - latency_test
  - frame_loss_rate_test
  - back_to_back_test