title: TestConfiguration
type: object
properties:
  topology_config:
    $ref: './TopologyConfig.yaml'
  frame_size_config:
    $ref: './FrameSizeConfig.yaml'
  multi_stream_config:
    $ref: './MultiStreamConfig.yaml'
  test_execution_config:
    $ref: './TestExecutionConfig.yaml'
required:
  - topology_config
  - frame_size_config
  - multi_stream_config
  - test_execution_config